network/project4/network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user_profile/<int:user_id>/", views.user_profile, name="user_profile"),
    path("user_profile/<int:user_id>/following/add", views.follow, name="follow"),
    path("user_profile/<int:user_id>/following/remove", views.unfollow, name="unfollow"),
    path("user_profile/<int:user_id>/following_list", views.following_list, name='following_list'),


    path("comment/<int:posts_id>/", views.comment, name="comment"),
    path("vote_rating/<int:posts_id>/", views.vote_rating, name="vote_rating"), 

    


    # API Routes
    path("comments", views.comment_api, name="comments"),
]
 

network/project4/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/project4/network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime
from django.utils import timezone

class User(AbstractUser):
    pass


    
class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name='user', related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=30, default='Name Edit Here' )
    bio = models.TextField(max_length=500,  default='Edit Bio Here')
    birth_date = models.DateField(null=True, blank=True, default='1900-01-01')
    location = models.CharField(max_length=100, blank=True, null=True, default='Location you live?')
    # picture = models.ImageField(upload_to='uploads/profile_pictures/', default='uploads/profile_pictures/default.png', blank=True)
    following = models.ManyToManyField(User, blank=True, related_name='following')
    friends_list = models.ManyToManyField(User, blank=True, related_name='friends_list')


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)
    comment = models.TextField(max_length=2000, default="Enter Comment Here")
    created_on = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

class Post(models.Model):
    posts = models.TextField(max_length=1337, default="Enter post here")
    posts_owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)
    date_and_time = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

network/project4/network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from django.http import JsonResponse
import json


def index(request):
    comments = Comments.objects.all()
    entries = Post.objects.all()
    if request.method == "POST":
        post = Post.objects.create(
            posts = request.POST['posts'],
            posts_owner = request.user
            )
        post.save()
        return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments}) 
    else:
        return render(request, "network/index.html",
        {"entries" : entries,
        "comments" : comments}) 
        
def vote_rating(request, posts_id):
    profile = User.objects.get(pk=request.user.pk)
    print('vote_rating function starting')
    post_linked = Post.objects.get(pk=posts_id)
    comments = Comments.objects.all()
    entries = Post.objects.all()
    if request.method != "POST":
        return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments,
        'profile' : profile}) 

    print(post_linked.rating)

    post_linked.rating = (int(request.POST['vote_input']) + post_linked.rating)
    post_linked.save()

    return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments,
        'profile' : profile}) 

#Fix a bug where where you need to track what url is 
# loaded when submitting comments and posts as not to 
# redirect just to the user_profile, but rather either to the 
# profile if needed to or to the all post if need be
#NON API View for comments
def comment(request, posts_id):
    print('comment function starting')
    post_linked = Post.objects.get(pk=posts_id)
    comments = Comments.objects.all()
    entries = Post.objects.all()
    if request.method != "POST":
        return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments}) 

    comment_data = request.POST["comment-input"]
    comment = Comments(
        user = request.user,
        comment = comment_data,
        post = post_linked
        )
    comment.save()

    return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments}) 


#API view for comment. CANT GET JS SCRIPT TO LOAD DUNNO IF WORKING
def comment_api(request):
    print('comment_api function starting')
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    print(request.POST)
    data = json.loads(request.body)
    print(data)
    comment_data = data.get("comment", "")
    comment = Comments(
        user = request.user,
        comment = comment_data,
    )
    comment.save()

    return JsonResponse({"message": "Comment Submitted."}, status=201)


def following_list(request, user_id):
    profile = User.objects.get(pk=user_id)
    following = profile.following.all()
    return render(request, "network/following.html",
    {"profile" : profile,
    'following' : following}) 


def follow(request, user_id):
    profile = UserProfile.objects.get(pk=user_id)
    profile.following.add(request.user)
    return redirect('user_profile', user_id=profile.pk)

def unfollow(request, user_id):
    profile = UserProfile.objects.get(pk=user_id)
    profile.following.remove(request.user)
    return redirect('user_profile', user_id=profile.pk)

def user_profile(request, user_id):
    profile = UserProfile.objects.get(pk=user_id)
    user = profile.user
    entries = Post.objects.all()
    following = profile.following.all()
    comments = Comments.objects.all()
    is_following = False

    for followed in following:
        if followed == request.user:
            is_following = True
            break
        else:
            is_following = False
 
    number_of_following = len(following)

    if request.method == "POST":
        post = Post.objects.create(
            posts = request.POST['posts'],
            posts_owner = request.user
            )
        post.save()
        return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments,
        'user': user,
        'profile': profile,
        'is_following': is_following,
        'number_of_following': number_of_following,}) 

    else:
        return render(request, "network/user_profile.html",
        {"entries" : entries,
        "comments" : comments,
        'user': user,
        'profile': profile,
        'is_following': is_following,
        'number_of_following': number_of_following,}) 



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        user_profile = UserProfile.objects.create(user=user)
        user_profile.save()
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

network/project4/network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}


{% block title %}Following List{% endblock title %}

{%block body %}

<h1>ALL USERS YOU ARE FOLLOWING</h1>


<div style=''>
    {% comment %} Lists the posts in an unordered list {% endcomment %}
    
<ul>
    {% for followed in following %}
       <li><a href="{% url 'user_profile' followed.user.pk %}">{{ followed.user }}</a> </li>
</ul>

{% endfor %}
</div>
{%endblock%}

network/project4/network/templates/network/index.html
{% extends "network/layout.html" %}

{% load static %}


{% block title %}User Social Media Wall{% endblock title %}

{%block body %}

<h1>ALL POSTS by ALL USERS</h1>
<form method="POST" class="user_posts">
    {% csrf_token %}
    
    
    <h3>Create a post</h3>
    <input type="text" id="id_posts" name="posts" placeholder="Create a post here...">
    
    <button type="submit" class="btn btn-success">Post</button>
    </form>
    
    

<div style=''>
    {% comment %} Lists the posts in an unordered list {% endcomment %}
    

    {% for msg_entry in entries %}
        <div style='background-color: #E2E2E2; border-style: solid'>  
            <div style='border-bottom: 5px solid'>
                <h4><a href="{% url 'user_profile' msg_entry.posts_owner.pk %}">{{ msg_entry.posts_owner }}</a>  on {{msg_entry.date_and_time}} wrote: <h4>
            </div>

            {% comment %} ACTUAL POST HERE {% endcomment %}
            <div style='border-bottom: 2px solid'>
                {{msg_entry.posts}} <br>   
            </div>

            {{msg_entry.rating}}
            <div style='align-content: center'> 

                            <form method="POST" action="{% url 'vote_rating' msg_entry.pk %}"  id="comment-form" style='align-content: right'>
                                {%csrf_token%}
                                <input type="hidden" name="vote_input" value='1'></input>
                                <button class ="" type='submit' id='post_vote_up'> Vote Up!</button>
                            </form>

                            <form method="POST" action="{% url 'vote_rating' msg_entry.pk %}"  id="comment-form" style='align-content: center'>
                                {%csrf_token%}
                                <input type="hidden" name="vote_input" value='-1'></input>
                                <button class ="" type='submit' id='post_vote_down'> Vote Down!</button>
                            </form>

            </div>
            
        </div>    
            <br>
            

        <form method="POST" action="{% url 'comment' msg_entry.pk %}"  id="comment-form">
        {%csrf_token%}
        <input type="text" name="comment-input" placeholder="Enter Comment Here"></input><br>
        <button class="btn btn-sm btn-outline-primary" type='submit' id="commentsubmit">Comment Submit</button>  
        </form>

    <br>


    {% comment %}  comments {% endcomment %}
            Comments: 
    <div style='border-style: solid; background-color: #C4C4C4;'>      
            {% for comment in comments %}
                {% if msg_entry.pk == comment.post.id %}
                    <li>{{comment.comment}}</li>
                    <br>    
                    
                {% endif %}     
        
            {% endfor %}
            
    {% comment %}  comments {% endcomment %}
    </div>
    <br>
    <br>
    <hr>
        
    {% endfor %}

</div>

<br>

{%endblock%}

network/project4/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        {% comment %} change the href below to the users profile page once you make the html page for it. {% endcomment %}
                        <a class="nav-link" href="{% url 'user_profile' user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'following_list' user.id %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
        </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/project4/network/templates/network/login.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

network/project4/network/templates/network/register.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

network/project4/network/templates/network/user_profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block script %}
    <script src="{% static 'network/comments.js' %}">
    </script>
{% endblock %}
<div style='  padding-top: 10px;
padding-bottom: 10px;
padding-right: 10px;
padding-left: 10px;'>

{% block title %}User Social Media Wall{% endblock title %}

{% block body %}

<h1>{{user}} User Profile</h1>
<div style='padding-bottom:200px'>

</div>


{% comment %} Follow or UnFollow {% endcomment %}
{% comment %} Follow {% endcomment %}
<form method="POST" action="{% url 'follow' profile.pk %}"  id="follow_form_id">
    {%csrf_token%}
    FOLLOW HERE
    <input type="hidden" name="follow-input" value='True' ></input><br>
    <button class="btn btn-sm btn-outline-primary" type='submit' id="followsubmit">Follow</button>  
    </form>

{% comment %} Un-Follow {% endcomment %}
 <form method="POST" action="{% url 'unfollow' profile.pk %}"  id="unfollow_form_id">
    {%csrf_token%}
    UN-FOLLOW
    <input type="hidden" name="follow-input" value='False'></input><br>
    <button class="btn btn-sm btn-outline-primary" type='submit' id="followsubmit">Un-Follow</button>  
    </form>




{% comment %} Create a new post here: {% endcomment %}

<form method="POST" class="user_posts">
{% csrf_token %}


<h3>Create a post</h3>
<input type="text" id="id_posts" name="posts" placeholder="Create a post here...">

<button type="submit" class="btn btn-success">Post</button>
</form>


<div style=''>
    {% comment %} Lists the posts in an unordered list {% endcomment %}
    

    {% for msg_entry in entries %}
        {% if msg_entry.posts_owner == user %}
        <div style='background-color: #E2E2E2; border-style: solid'>  
            <div style='border-bottom: 5px solid'>
                <h4>{{msg_entry.posts_owner}} on {{msg_entry.date_and_time}} wrote: <h4>
            </div>
            <div style='border-bottom: 2px solid'>
                {{msg_entry.posts}} <br>   
            </div>
            {{msg_entry.rating}}
            <div style='align-content: center'> 

                            <form method="POST" action="{% url 'vote_rating' msg_entry.pk %}"  id="comment-form" style='align-content: right'>
                                {%csrf_token%}
                                <input type="hidden" name="vote_input" value='1'></input>
                                <button class ="" type='submit' id='post_vote_up'> Vote Up!</button>
                            </form>

                            <form method="POST" action="{% url 'vote_rating' msg_entry.pk %}"  id="comment-form" style='align-content: center'>
                                {%csrf_token%}
                                <input type="hidden" name="vote_input" value='-1'></input>
                                <button class ="" type='submit' id='post_vote_down'> Vote Down!</button>
                            </form>

            </div>
            
        </div>    
            <br>
            

        <form method="POST" action="{% url 'comment' msg_entry.pk %}"  id="comment-form">
        {%csrf_token%}
        <input type="text" name="comment-input" placeholder="Enter Comment Here"></input><br>
        <button class="btn btn-sm btn-outline-primary" type='submit' id="commentsubmit">Comment Submit</button>  
        </form>

    <br>


    {% comment %}  comments {% endcomment %}
            Comments: 
    <div style='border-style: solid; background-color: #C4C4C4;'>      
            {% for comment in comments %}
                {% if msg_entry.pk == comment.post.id %}
                    <li>{{comment.comment}}</li>
                    <br>    
                    
                {% endif %}     
        
            {% endfor %}
            
    {% comment %}  comments {% endcomment %}
    </div>
    <br>
    <br>
    <hr>


        {% else %}
        


        {% endif %}
        
    {% endfor %}

</div>

<br>

{%endblock%}