secrect_santa/accounts/urls.py
from django.urls import path

from . import views


app_name = "acc"


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('santas_list_signup/', views.santas_list_signup, name='santas_list_signup'),
    path('santascontrol/', views.santascontrol, name= 'santascontrol'),
]

secrect_santa/secrect_santa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

secrect_santa/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    email = models.EmailField(max_length=500, default="what is your Email?")


class SantasList(models.Model):
    name = models.CharField(max_length=15)
    email = models.EmailField(max_length=30)
    

secrect_santa/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User, SantasList


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2"
            ]



class SantasListForm(forms.ModelForm):
    class Meta:
        model = SantasList
        fields = [
            "name",
            "email",
        ]

secrect_santa/accounts/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from .forms import RegisterForm, SantasListForm
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from django.contrib.auth import get_user_model, authenticate, login, logout
import smtplib, ssl
import random

# Create your views here.
from django.http import HttpResponse

User = get_user_model()


def index(request):
    return render (request, 'accounts/home.html', {})


def login_user(request):
    if request.method == "GET":
        return render(request, "accounts/login_user.html")
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
            )
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('acc:index'))
        else:
            return HttpResponse("Invalid Username and or Password")


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("acc:index")
    else:
        form = RegisterForm()

    return render(
        request,
        "accounts/create_user.html",
        {"form": form}
        )


def logout_user(request):
    logout(request)
    return render(request, "accounts/logged_out.html")

def santas_list_signup(request):
    if request.method == "POST":
        form = SantasListForm(request.POST)
        if form.is_valid():
            form.save()
        return render(request, "accounts/santas_list_signup_succ.html")
    else:
        form = SantasListForm()
        return render(
            request,
            "accounts/santas_list_signup.html",
            {"form": form}
            )

def send_email(user, receiver_email):
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = "python5212@gmail.com"  # Enter your address
    receiver_email = f"{receiver_email}"  # Enter receiver address
    password = 'ur8grwd8'
    message = f'''
                Your secrect santa is {user}..

                Merry Xmas!!


                '''

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message)



def santascontrol(request):
    if request.method == "POST":
        avoid_pairs = {} #{'Ryan': 'a', 'Robert': 'z'}
        avoid_users = list(request.POST) #['csrfmiddlewaretoken', 'Ryan', 'Robert']
        avoid_users.remove('csrfmiddlewaretoken')
        santas_list = SantasList.objects.all()
        for avoid_user in avoid_users:
            avoid_pairs[avoid_user] = request.POST[f'{avoid_user}']


        pairs = {}

        while len(avoid_users) > 1:

            #Using the randomly created indices, respective elements are popped out
            r1 = random.randrange(0, len(avoid_users))
            elem1 = avoid_users.pop(r1)

            r2 = random.randrange(0, len(avoid_users))
            elem2 = avoid_users.pop(r2)

            if avoid_pairs[elem1] != avoid_pairs[elem2]:
            # now the selecetd elements are paired in a dictionary 
                pairs[elem1] = elem2
            else:
                avoid_users.append(elem1)
                avoid_users.append(elem2)

        print(pairs)

        for paired in pairs:
            user1 = paired
            user2 = pairs[paired]
            print(user1)
            print(user2)


#UNCOMMENT WHEN YOU WANT TO ACTUALLY SEND OUT EMAILS
            # obj_user1 = SantasList.objects.get(name = str(user1))
            # obj_user2 = SantasList.objects.get(name = str(user2))

            # send_email(user1, obj_user1.email)
            # send_email(user2, obj_user2.email)
            
        return render(request, "accounts/santas_list_signup_succ.html")


    else:
        santaslist = SantasList.objects.all()
        return render(request, "accounts/santas_list_view_admin.html", {"santaslist": santaslist})

secrect_santa/accounts/templates/accounts/base.html
{% load static %}

<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">

{% comment %} #nav bar {% endcomment %}
    <style type="text/css">
        .sidenav {
            height:100%;
            width:160px;
            position: fixed;
            z-index:1;
            top:0;
            Left:0;
            background-color:#111;
            overflow-x: :hidden;
            padding-top:20px;

        }

        .sidenav a {
            padding:6px 8px 6px 16px;
            text-decoration:none;
            font-size:25px;
            color: #818181;
            display:block;
            
        }

        .sidenav a:hover{
            color:#f1f1f1;
        }

        .main{
            margin-Left:160px;
            padding: 0px 10px;
        }


    </style> 

 

    <title> {% block title %} Lifter Site {% endblock %} </title>
    {% block style%}{% endblock %}
    
</head>



<body>
    <div class="sidenav">
       {% if user.is_authenticated %}
            <p>
            you are logged in
            <a href="{%url "acc:logout_user" %}"> logout </a>
            <a href="{%url "acc:index" %}"> Home </a>
            <a href="{%url "acc:santas_list_signup" %}"> Santas List Signup </a>
            <a href="{%url "acc:santascontrol" %}"> santas control ADMIN </a>


            </p>
        {%else%}
            <p>
            not logged in
            <a href="{%url "acc:index" %}"> Home </a> 
            <a href="{%url "acc:login_user" %}"> login </a>
            <a href="{%url "acc:register" %}"> register </a>
            </p>
        {%endif%}


    </div>

    <div id="content", name="content", class="main">
        {% block content %}
        {% endblock%}
    </div>

</body>
</html>

secrect_santa/accounts/templates/accounts/create_user.html
{% extends "accounts/base.html"%}

{% block title %} Register New User {% endblock%}

{%block content %}
<h1>Register</h1>


    <form method="POST" class="form-group">
	{% csrf_token %}
	{{ form }}
	<button type="submit" class="btn btn-success">Register</button>
    </form>

{%endblock%}

secrect_santa/accounts/templates/accounts/home.html
{% extends "accounts/base.html"%}

{% block title %} Home {% endblock %}


{%block content %}

<h1> Home </h1>

<p>Secrect Santa List</p>

{% if user.is_authenticated %}
    <p> {{user}} Logged In</p>
{%else%}
    <p> Not Logged in </p>

{%endif%}

<p>lorem ipsum dolor sit amet, consectet lorem ipsum dolor sit amet</p>

{%endblock%}

secrect_santa/accounts/templates/accounts/logged_out.html
{% extends "accounts/base.html" %}

{% block content %}
  <p>Logged out!</p>
  <a href="{% url 'acc:login_user'%}">Click here to login again.</a>
{% endblock %}

secrect_santa/accounts/templates/accounts/login_user.html
{% extends "accounts/base.html"%}

{% block title %} LogIn {% endblock %}


{%block content %}

<h1> LogIn </h1>



<form action="" method="POST">
    {% csrf_token %}
    <label for="username">Enter Username: </label>
    <input id="username" type="username" name="username" value="username">
    </br>
    <label for="password">Enter Password </label>
    <input id="password" type="password" name="password" value="password">
    </br>
    <input type="submit" value="OK">
</form>

<a href="{%url 'acc:register'%}">Register</a>

{%endblock%}

secrect_santa/accounts/templates/accounts/santas_list_signup.html
{% extends "accounts/base.html"%}

{% block title %} Santas List {% endblock%}

{%block content %}
<h1>Sign Up for Secrect Santa</h1>


    <form method="POST" class="form-group">
	{% csrf_token %}
	{{ form }}
	<button type="submit" class="btn btn-success">Sign Up! Santas List Sign Up!</button>
    </form>

{%endblock%}

secrect_santa/accounts/templates/accounts/santas_list_signup_succ.html
{% extends "accounts/base.html"%}

{% block title %} Home {% endblock %}


{%block content %}

<h1> Santas List Sign Up Successful!! </h1>

<p>Secrect Santa List SignUp Successfully completed</p>

{%endblock%}

secrect_santa/accounts/templates/accounts/santas_list_view_admin.html
{% extends "accounts/base.html"%}

{% block title %} admin controls {% endblock %}


{%block content %}

<h1> santas list admin </h1>

<p>Secrect Santa List control</p>

{% if user.is_authenticated %}
    {% comment %} <p> {{user}} Logged In</p> {% endcomment %}

<p>

    <form class="button" id="user_selection" action="" method='post'>
    {% csrf_token %}

    {% for user in santaslist %}
    
    <br><p> {{user.name}} has signed up with an email address: {{user.email}}</p>

    <input type="text" name="{{user.name}}" placeholder="A,B,C"><br>

    {%endfor%}

    <input type="submit" value="submit">
    </form>

   

    create button that when hit will randomly assign pairs using the names on the santas List
    the button will make sure NOT to pair the preselected pairs on...

    Email all santas list users there paired partners name and email and description
</p>


{%else%}
    <p> Not Logged in </p>

{%endif%}


{%endblock%}